### ISSUE TITLE
big_core - add  global defines

### ISSUE THREAD

**Issue by danielk532** [FPGA-MAFIA/fpga_mafia#107]
add global defines under - /source/big_core/global_defines.txt

**Comment by amichai-bd** [comment]
There should be global definitions per core/configuration.
Example:
- fat_big_core_global_defines        // larger memory foot print
- thin_big_core_global_defines      // smaller memory foot print
- fat_mini_core_global_defines      // larger memory foot print
- thin_mini_core_global_defines    // smaller memory foot print
