### ISSUE TITLE
Fabric - create the uart_io tile

### ISSUE THREAD

**Issue by amichai-bd** [FPGA-MAFIA/fpga_mafia#297]
The uart_io tile will instantiate the uart_io and will connect correctly to the Fabric STD interface.
You may need to fix the uari_io itself in the process.

This is to allow use of the uart in the fabric without dependency on the big_core.
this means that 1 of the tiles is a 'uart' tile and it has no "local_mini_core".
This can make things difficult in the general XMR we created - need to figure out what is the best practice to integrate the uart_io without breaking to current verification env.

**Comment by ShmuelSfez** [comment]
@amichai-bd i prefer to take part on creating this.
thanks.
