### ISSUE TITLE
RRV - Integrate the new "Roman RiscV" into the MAFIA project

### ISSUE THREAD

**Issue by amichai-bd** [FPGA-MAFIA/fpga_mafia#351]
- No need to integrate nto the fabric
- We want to utilize the MAFIA TFM (APP, Build, reference model) to run the RRV project.

**Comment by amichai-bd** [comment]
@roman012285  - This we will do together next week in our 1:1

**Comment by roman012285** [comment]
NOT RELEVANT! WE DELETE THAT CORE

**Comment by amichai-bd** [comment]
Please close this type of issues as "no-planned" and not as complited.
Also - PLease do not update the milestone to MAFIA 1.0 -> The mile stone should stay at it original date unless we want to push it to a later dat

**Comment by amichai-bd** [comment]
see example here:
![image](https://github.com/FPGA-MAFIA/fpga_mafia/assets/81047407/0c621247-350f-4839-a878-a24f837079ad)
