### ISSUE TITLE
Improve csr.h file

### ISSUE THREAD

**Issue by amichai-bd** [FPGA-MAFIA/fpga_mafia#417]
Here is a memory-efficient alternative (Chate GPT suggestion when i asked it to use macro instead of functions)
/*******************************************************
 * RISC-V Interrupts and Exceptions CSR read macros
*******************************************************/

#define READ_CSR(reg) ({ int __val; asm volatile ("csrr %0, " #reg : "=r"(__val)); __val; })

#define read_mcause() READ_CSR(mcause)
#define read_mepc() READ_CSR(mepc)
#define read_mtval() READ_CSR(mtval)
#define read_mstatus() READ_CSR(mstatus)
#define read_mie() READ_CSR(mie)
#define read_mip() READ_CSR(mip)

**Comment by roman012285** [comment]
Thanks, will be done as soon as posiible
