### ISSUE TITLE
add HW interrupt support to core_rrv

### ISSUE THREAD

**Issue by roman012285** [FPGA-MAFIA/fpga_mafia#437]
The interrupt will start when one of the counters will reach a predefined value.

**Comment by amichai-bd** [comment]
@roman012285 - How is this going?
Any update on progress?

**Comment by roman012285** [comment]
Hi, I took a small break cause I have to record a few lessons in one of the courses I am selling  I an comming back on thusday. Please dont start working on that by yourself let me 🤣
