### ISSUE TITLE
core_rrv - create a dedicated test for the timer interrupt during a illegal instruction trap

### ISSUE THREAD

**Issue by amichai-bd** [FPGA-MAFIA/fpga_mafia#477]
Create a test that has both "illegal instruction trap" and "timer interrupts".

I am hoping to see hit this case:

- illegal instruction trap exception handler is in progress (MIE set to 0 by HW)
- Timer interrupt time condition met -> but MIE is 0, so no exception is taken yet
- illegal instruction handler return with MRET (MIE back to 1)
- Timer interrupt condition is still set so the timer interrupt exception handler takes place
- We return from the timer interrupts and continue execution

**Comment by roman012285** [comment]
Sure
