### ISSUE TITLE
Document what is a FPGA  vs ASIC

### ISSUE THREAD

**Issue by amichai-bd** [FPGA-MAFIA/fpga_mafia#481]
Please under the discussion tab, add a new discussion describing the differents between ASIC & FPGA.
focus on the FPGA aspic.
Use the DE10-lite as example.

You may use ChatGPT to answer your many questions.

**Comment by amichai-bd** [comment]
Please provide ETA for completing this task

**Comment by amichai-bd** [comment]
@jacobavitan837 - Kind reminder

Let me know if you need assistance - this is a 5-15 minute task

**Comment by amichai-bd** [comment]
Done:
 https://github.com/FPGA-MAFIA/fpga_mafia/discussions/529

**Comment by NoamRahat** [comment]
[FPGA or ASIC .pdf](https://github.com/FPGA-MAFIA/fpga_mafia/files/14820417/FPGA.or.ASIC.pdf)
