### ISSUE TITLE
Add a-j to print function in vga lib

### ISSUE THREAD

**Issue by NoamRahat** [FPGA-MAFIA/fpga_mafia#531]

**Comment by NoamRahat** [comment]
@jacobavitan837 please assign yourself

**Comment by amichai-bd** [comment]
Added a script to create the bit pixel representation of the ascii char.

Please use it for this task 

@jacobavitan837 - please assign yourself to this task

**Comment by amichai-bd** [comment]
I added a script to create the bit pixel representation of the ascii char.
> https://github.com/FPGA-MAFIA/fpga_mafia/blob/main/scripts/ascii_pixle_gen.py  

Please use it for this task
