### ISSUE TITLE
Add k-t to print function in vga lib

### ISSUE THREAD

**Issue by NoamRahat** [FPGA-MAFIA/fpga_mafia#532]

**Comment by amichai-bd** [comment]
[font.zip](https://github.com/FPGA-MAFIA/fpga_mafia/files/14527076/font.zip)
I think file may help -> you should look at this implementation and see how it compares to ours.
Then you can extract the correct method to copy the pixel map to our way of doing this

**Comment by amichai-bd** [comment]
https://lpc.opengameart.org/content/8x8-ascii-bitmap-font-with-c-source
![image](https://github.com/FPGA-MAFIA/fpga_mafia/assets/81047407/c62e4bc1-7da9-4782-9c67-3163bd6601bf)

**Comment by amichai-bd** [comment]
Added a script to create the bit pixel representation of the ascii char.

Please use it for this task

**Comment by NoamRahat** [comment]
under review: https://github.com/FPGA-MAFIA/fpga_mafia/pull/537

**Comment by amichai-bd** [comment]
![image](https://github.com/FPGA-MAFIA/fpga_mafia/assets/81047407/3b225ecf-caab-411c-aa60-147388ef64a2)
Seems like this is Done.
I think you can close this issue

**Comment by NoamRahat** [comment]
Done.
