### ISSUE TITLE
`core_rrv` has been renamed to `big_core` - ONLY READ ISSUE

### ISSUE THREAD

**Issue by roman012285** [FPGA-MAFIA/fpga_mafia#621]
hi @jacobavitan837  and @NoamRahat. 
The core formerly known as `core_rrv` has been renamed to `big_core`. The organizational structure, including folders, tests, and all files, remains unchanged from its previous incarnation under `core_rrv`.

Please note, the build command referencing `-dut core_rrv` **is no longer valid** . Replace it with big_core in your commands. For example, use the following command to build:
```
./build.py -dut big_core -test alive_vga -hw -sim
```
Please note here that you red this and for the last person reviewing this issue, please ensure to close it.

- [x]  jacobavitan837
- [x] NoamRahat

**Comment by NoamRahat** [comment]
![image](https://github.com/FPGA-MAFIA/fpga_mafia/assets/96725773/d8954ddb-02dc-4b97-a884-ca202bc20835)

**Comment by roman012285** [comment]
1.Add the -app flag
2.I think you missing a library that has to he installed. Please work with chatgpt on such errors

**Comment by roman012285** [comment]
1.Add the -app flag
2.I think you missing a library that has to he installed. Please work with chatgpt on such errors
3. IMPORTANT - do git pull before doing anything.

**Comment by NoamRahat** [comment]
to solve the issue, open a terminal or command prompt and run the following command:

```
pip install termcolor
```

Once the installation is complete, try running your script again, and it should work without any issues.
