### ISSUE TITLE
Organize the mem_ss source directory. 

### ISSUE THREAD

**Issue by amichai-bd** [FPGA-MAFIA/fpga_mafia#656]
Please create a new directory "sdram_ctrl" and move the files into it.

- Make sure the FPGA compilation is still working
- Make sure the simulation (if we have any) are still working

**Comment by amichai-bd** [comment]
388 file changed!
This is not a good sign..
![image](https://github.com/FPGA-MAFIA/fpga_mafia/assets/81047407/6da56767-04ac-4b5d-bf13-ad1fc77b9fef)

Please make sure you committed only whats needed

**Comment by roman012285** [comment]
I know, I forgot to add files to .gitignore
I modified git ignore after the commit
