### ISSUE TITLE
Design of a basic tracker of performance in your dedicated mini_core

### ISSUE THREAD

**Issue by roman012285** [FPGA-MAFIA/fpga_mafia#704]
## Design a basic tracker to show the core performance in terms of IPC (Instructions Per Cycle):

The tracker will consist of two parts:

### Counters:

- Increment the clock cycle counter on each clock cycle.
- Increment the valid instruction counter each time a valid instruction is executed.

### IPC Calculation and Display:

- Upon detecting an EBREAK instruction, divide the valid instruction counter by the clock cycle counter.
- Display the resulting IPC value.

**Comment by erez-sh** [comment]
done. pushed to mini_core_trackers branch.
