### ISSUE TITLE
Understand mini_core design 

### ISSUE THREAD

**Issue by roman012285** [FPGA-MAFIA/fpga_mafia#749]
- [x] run `example.c` and examine the `main` function  and how `mini_core` performs it
- [x] Examine the trackers inside the `target/mini_core` directory
- [x] use the following [line] (https://fpga-mafia.github.io/fpga_mafia_wiki/docs/rvc/intro)
- [x] add custom instruction `add_inc` for example `add_inc x1, x2, x3 => x1 = x1 + x2 + 1`
use inline assembly `    //asm(".word 0xf4f757a3" : /* outputs / : / inputs / : / clobbers */);`
- [x] check the functionality of the instruction using the right tackers

`./build.py -dut mini_core -test example -app` - compile compile.c test
`./build.py -dut mini_core -test example -app -hw -sim` - compile the design (-hw flag) + simulate and elaboration (-sim flag)

**Comment by abdkeb** [comment]
Hi Roman,

here is the line of code we added to the exampl.c file:
![image](https://github.com/user-attachments/assets/4e575858-df14-4bc6-9bcd-0a4c4e2eec2b)

Here is the code in binary and the log of the registers:
![image](https://github.com/user-attachments/assets/4297d190-d235-4543-b3dc-f43d949de9e4)

**Comment by roman012285** [comment]
How you prove that it works, I dont see it from the tracker.

**Comment by abdkeb** [comment]
here i opened the tracker file in two windows the line is 17c and we can see that prior to the reg x16 was zero after it has 0xf+0xa+1 = 0x1a
![image](https://github.com/user-attachments/assets/26e2f324-abe7-4a35-abc9-3e3ee84791d6)

**Comment by roman012285** [comment]
Great Job!
